[server]
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#414582ff"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

